#!/bin/bash
# Config Management Tools
configs=("bash" "nvim" "wt")

# Config paths
config_path_bash=~

if [[ $OS == "Windows" ]]; then
  config_path_wt=~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/
  config_path_nvim=~/AppData/Local/nvim
elif [[ $OS == "Linux" ]]; then
  config_path_nvim=~/.config/nvim
elif [[ $OS == "Darwin" ]]; then
  : # Nothing here yet
fi

# Long Names of Configs
config_name_bash=Bash
config_name_wt="Windows Terminal"
config_name_nvim=NeoVim

config_command() {
  command="$1"
  name="$2"
  path="$3"

  echo > /dev/stdout
  clr_bold clr_green "[$name] $path" > /dev/stdout
  git -C "$path" $command > /dev/stdout
}

cmt() {
  command="$1"
  config="$2"
  help_msg="cmt: Need a git command to execute.\nPossible Commands:\n  - status\n  - pull\n  - push"

  if [[ -z $command ]]; then
    echo -e $help_msg
    return 1
  fi

  if [[ -n $config ]]; then
    name_var="config_name_${config}"
    path_var="config_path_${config}"
    config_command $command "${!name_var}" "${!path_var}"
  else
    for cfg in ${configs[@]}; do 
      name_var="config_name_${cfg}"
      path_var="config_path_${cfg}"
      config_command $command "${!name_var}" "${!path_var}"
    done
  fi
}
