#!/bin/bash

# ls aliases
alias l="ls"
alias la="ls -A"
alias ll="ls -hl"
alias lla="ls -hlA"

if [[ $OS == "Windows" ]]; then
  alias lh="ls -d .?*"
  alias llh="ls -ld .?*"
else
  alias lh="ls -d .!(|.)"
  alias llh="ls -hld .!(|.)"
fi

# vim aliases
alias vim="nvim"
alias vi="vim"

# python aliases
alias ipy="ipython"
alias py="python"
alias pyenv="pyenv_wrapper"
alias pye="pyenv"
alias venv="python -m venv"

# other
alias qmake="qmake-qt5"
alias lg="lazygit"
