#!/bin/bash

# Starts tmux if the current session isn't tmux yet
#if [ -z ${TMUX+x} ]; then
#    tmux
#fi
# Better alternative
# Source: https://stackoverflow.com/a/51922746
if [ -t 0 ] && [[ -z $TMUX ]] && [[ $- = *i* ]]; then exec tmux; fi

